site_name: ClinLang

theme:
  name: material

docs_dir: docs

nav:
  - Home: README.md
  - Quick Start: quickstart.md
  - Commands: commands.md
  - FAQ: faq.md
  - Reference Ranges: reference-ranges.md
  - Special Cases: special-cases.md
  - Customization: customization.md
  