// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from pkg/workspace. DO NOT EDIT BY HAND.
// Regenerate via `make types`.

/* eslint-disable */

//////////
// source: workspace.go
/*
Package workspace provides filesystem-backed storage for ClinLang
notes (.cln files) and associated workspace metadata. It is the same
abstraction used by the HTTP API server in both local and hosted
deployment modes; the deployment-mode caller is responsible for
selecting the appropriate root (per-user in hosted mode, single
shared root in local mode) before constructing a LocalFileSystem.

All public methods reject paths that resolve outside the configured
root. There is no escape hatch.
*/

/**
 * FileEntry is a single node in a workspace listing.
 */
export interface FileEntry {
  name: string;
  path: string;
  is_dir: boolean;
  items?: FileEntry[];
}
/**
 * LocalFileSystem is a filesystem-backed workspace rooted at RootDir.
 * All caller-supplied paths are treated as relative; absolute paths are
 * re-interpreted as relative, and "../" sequences cannot climb above
 * RootDir.
 */
export interface LocalFileSystem {
  RootDir: string;
}
