// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from pkg/autocomplete. DO NOT EDIT BY HAND.
// Regenerate via `make types`.

/* eslint-disable */

//////////
// source: autocomplete.go
/*
Package autocomplete provides suggestion lookups for the editor UI.
It wraps the engine's drug list with a small static dictionary of
command-keyword suggestions; it is NOT a parser or a clone of the
engine.
*/

/**
 * Suggestion is a single autocomplete result for the frontend.
 */
export interface Suggestion {
  label: string;
  value: string;
  description: string;
  category: string;
}
