// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from pkg/engine. DO NOT EDIT BY HAND.
// Regenerate via `make types`.

/* eslint-disable */

//////////
// source: formatters.go

/**
 * FormatOptions controls how exported formats render optional sections.
 * The zero value is the safe default: out-of-range markers are suppressed.
 * Callers opt in to marker rendering by setting ShowRangeMarkers to true.
 */
export interface FormatOptions {
  ShowRangeMarkers: boolean;
}

//////////
// source: models.go

/**
 * Vitals holds structured vital signs.
 * Temperature carries an explicit TempUnit ("F" or "C"). Inputs without
 * a unit suffix default to "F". The engine never converts between
 * units — out-of-range markers fire only when the recorded TempUnit
 * matches the reference range's configured unit.
 */
export interface Vitals {
  BP: string;
  HR: number /* int */;
  SpO2: number /* int */;
  Temp: number /* float64 */;
  temp_unit?: string;
  RR: number /* int */;
}
/**
 * Symptom holds a single symptom with optional intensity and duration.
 */
export interface Symptom {
  name: string;
  intensity: string;
  duration: string;
  frequency: number /* int */;
}
/**
 * Patient holds demographic information.
 */
export interface Patient {
  id: string;
  age: number /* int */;
  age_unit?: string;
  sex: string; // M/F/O
  weight_kg: number /* float64 */; // wt68
  height_cm: number /* float64 */; // ht170
  bed: number /* int */; // bed number
  unit: string; // Unit type
  bmi: number /* float64 */; // Body mass index auto-calculated
  bsa: number /* float64 */; // body surface area auto-calculated
  blood_group?: string; // Blood Group
}
export interface ClinicalFlags {
  is_pregnant: boolean; // Pregnancy Indicator
  is_lactating: boolean; // Lactation indicator
}
export interface ClinicalCase {
  profile?: string; // ClinicalCase profile
  patient: Patient; // Patient Information
  day?: string; // Rounding day/event timeline
  allergies?: string; // Allergies
  cc?: string; // Chief complaint
  hpi?: string; // History of presenting illness
  pmh?: string; // Past medical history
  sh?: string; // Social history
  fh?: string; // Family history
  pe?: string; // Physical/Objective exam
  dx?: string; // Provisional Diagnosis
  ddx?: string; // Differential Diagnosis
  vitals: Vitals; // Vital signs
  symptoms: Symptom[]; // Symptoms slice of Symtoms struct
  labs?: { [key: string]: string}; // Structured labs dictionary
  imaging?: { [key: string]: string}; // Structured radiology/imaging
  prescriptions?: Prescription[]; // Prescriptions
  extra?: { [key: string]: { [key: string]: string}}; // Extra information
  specialty_data?: unknown; // Specialty data
  range_markers?: RangeMarker[]; // Out-of-range markers derived from user-configurable reference ranges (transcription aid, not clinical decision support)
  clinical_flags: ClinicalFlags; // Clinical flags patient already have such as pregnancy, lactation, etc
  warnings?: string[]; // Warnings
}

//////////
// source: parser.go

export type ParserFunc = unknown;

//////////
// source: prescription_parser.go

/**
 * Prescription represents a single medication order.
 */
export interface Prescription {
  drug: string;
  dose: string; // e.g. "25mg", "500mg"
  frequency: string; // e.g. "BD", "OD"
  route: string; // e.g. "IV", "PO" (optional)
  duration: string; // e.g. "7d", "5d" (optional)
}

//////////
// source: range_markers.go

/**
 * RangeMarker is a neutral, transcription-only annotation that a value
 * recorded in a ClinicalCase falls outside a user-configurable reference
 * range. It is NOT a clinical interpretation. The clinician decides
 * whether and how the marker is meaningful.
 * See DISCLAIMER.md at the repository root.
 */
export interface RangeMarker {
  field: string;
  value: string;
  reference_range: string;
  source: string;
  out_of_range: boolean;
}
/**
 * Range describes one reference band loaded from reference_ranges.json.
 * Low and High are pointers so a one-sided range (only an upper or lower
 * bound) is expressible.
 */
export interface Range {
  low?: number /* float64 */;
  high?: number /* float64 */;
  unit?: string;
  source: string;
}
/**
 * ReferenceRanges is keyed by dotted path, e.g. "vitals.hr" or "labs.hb.M".
 */
export type ReferenceRanges = { [key: string]: Range};

//////////
// source: registry.go

/**
 * SpecialtyPlugin defines the mandatory contract for all specialty plugins.
 * Every plugin must implement this interface.
 */
export type SpecialtyPlugin = unknown;
/**
 * TokenExtFunc is the handler signature for an inline token extension.
 * When a core command parser encounters an unrecognized token, it consults
 * the CommandTokenRegistry. If a matching extension is found, this function
 * is called with the raw token and the ClinicalCase.
 * Rules for plugin authors:
 *   - Return true  → you handled the token; parser continues silently.
 *   - Return false → you did not handle it; parser falls through to warning.
 *   - ONLY write into c.SpecialtyData — never into c.Patient or other core fields.
 *   - Always type-assert c.SpecialtyData safely (check the bool).
 */
export type TokenExtFunc = unknown;
/**
 * CommandExtendable is an OPTIONAL interface plugins may implement.
 * It allows a plugin to register inline token handlers for any existing core
 * command without modifying the core engine source.
 * Return value layout:
 * 	map[commandName]map[tokenPrefix]TokenExtFunc
 * 	     "pt"           "ga:"          handler
 * 	     "vitals"       "fhr:"         handler
 * Token prefixes are matched case-insensitively with strings.HasPrefix.
 * Use a colon suffix (e.g. "ga:") to clearly delimit prefix from value.
 * Example usage in a .cln file (when @profile is declared first):
 * 	@profile obgyn
 * 	pt 28F wt65 ga:34w       ← "ga:" handled by obgyn's pt extension
 * 	vitals bp120/75 fhr:142  ← "fhr:" handled by obgyn's vitals extension
 */
export type CommandExtendable = unknown;
/**
 * CommandTokenRegistry holds all active token extensions for one parse session.
 * It is created fresh inside ParseString() — there is NO global state.
 * This guarantees that extensions registered for an OB/GYN case never bleed
 * into a Cardiology case parsed in the same process.
 */
export interface CommandTokenRegistry {
}
/**
 * PluginInfo is a serialisable summary of a plugin for the frontend.
 */
export interface PluginInfo {
  name: string;
  description: string;
  commands: { [key: string]: string};
}
