package engine

import (
	"encoding/json"
	"fmt"
	"strings"
)

// FormatJSON produces a standard JSON representation of the ClinicalCase.
func FormatJSON(c ClinicalCase) string {
	b, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return "{ \"error\": \"Failed to format JSON\" }"
	}
	return string(b)
}

// FormatMarkdown produces a "Beautifully Written" markdown document of the encounter.
func FormatMarkdown(c ClinicalCase) string {
	var sb strings.Builder

	// Title & Patient Header
	sb.WriteString(fmt.Sprintf("# Clinical Summary: %s\n\n", c.Patient.Id))
	
	sb.WriteString("## Patient Information\n")
	sb.WriteString(fmt.Sprintf("- **Profile**: %s\n", formatPatientLine(c.Patient)))
	if c.Day != "" {
		sb.WriteString(fmt.Sprintf("- **Timeline**: %s\n", c.Day))
	}
	if c.Allergies != "" {
		sb.WriteString(fmt.Sprintf("- **Allergies**: %s\n", c.Allergies))
	}
	sb.WriteString("\n")

	// Subjective
	sb.WriteString("## Subjective\n")
	if c.CC != "" {
		sb.WriteString(fmt.Sprintf("- **Chief Complaint**: %s\n", c.CC))
	}
	if c.HPI != "" {
		sb.WriteString(fmt.Sprintf("- **HPI**: %s\n", c.HPI))
	}
	if c.PMH != "" {
		sb.WriteString(fmt.Sprintf("- **PMH**: %s\n", c.PMH))
	}
	
	if len(c.Symptoms) > 0 {
		sb.WriteString("- **Active Symptoms**:\n")
		for _, s := range c.Symptoms {
			sb.WriteString(fmt.Sprintf("  - %s", s.Name))
			if s.Intensity != "" || s.Duration != "" {
				sb.WriteString(" (")
				parts := []string{}
				if s.Intensity != "" { parts = append(parts, s.Intensity) }
				if s.Duration != "" { parts = append(parts, ExpandDuration(s.Duration)) }
				sb.WriteString(strings.Join(parts, ", "))
				sb.WriteString(")")
			}
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\n")

	// Objective
	sb.WriteString("## Objective\n")
	sb.WriteString(fmt.Sprintf("- **Vital Signs**: %s\n", FormatVitals(c.Vitals)))
	if c.PE != "" {
		sb.WriteString(fmt.Sprintf("- **Examination**: %s\n", c.PE))
	}
	
	if len(c.Labs) > 0 {
		sb.WriteString("- **Investigations**:\n")
		for k, v := range c.Labs {
			val := v
			if val == "true" { val = "Ordered" }
			sb.WriteString(fmt.Sprintf("  - %s: %s\n", strings.ToUpper(k), val))
		}
	}
	
	if len(c.AbnormalFlags) > 0 {
		sb.WriteString("\n### Clinical Alerts\n")
		for _, f := range c.AbnormalFlags {
			sb.WriteString(fmt.Sprintf("- **%s**: %s (%s)\n", f.Field, f.Value, f.Severity))
		}
	}
	sb.WriteString("\n")

	// Assessment
	sb.WriteString("## Assessment\n")
	diag := c.DX
	if diag == "" { diag = "TBD" }
	sb.WriteString(fmt.Sprintf("- **Diagnosis**: %s\n", diag))
	if c.DDX != "" {
		sb.WriteString(fmt.Sprintf("- **Differentials**: %s\n", c.DDX))
	}
	sb.WriteString("\n")

	// Plan
	sb.WriteString("## Plan\n")
	if len(c.Prescriptions) > 0 {
		sb.WriteString("### Prescriptions\n")
		for _, p := range c.Prescriptions {
			sb.WriteString(fmt.Sprintf("- **%s** %s %s, %s for %s\n", 
				titleCase(p.Drug), p.Dose, p.Route, p.Frequency, ExpandDuration(p.Duration)))
		}
	} else {
		sb.WriteString("*No prescriptions documented.*\n")
	}

	sb.WriteString("\n---\n")
	sb.WriteString("*Generated by ClinLang Engine*")

	return sb.String()
}
